version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    env_file: ./.env.development
    container_name: develivery_much_challenge
    environment:
      - NODE_ENV=development
    volumes:
    - $PWD:/var/www/app
    ports:
    - 3000:3000
    networks:
    - dmuch-network


volumes:
  nodemodules: {}

networks:
  dmuch-network:
    driver: bridge
