name: Delivery Much Challenge

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Running tests
      run: npm test -u
      env:
        GIPHY_API_TOKEN: __TOKEN__
        GIPHY_API_ENDPOINT: __ENDPOINT__
        RECIPEPUPPY_ENDPOINT: __ENDPOINT__
        APP_PORT: 3000

